Fix modal
roll-network/tryrolljs pull request #432
Opened 2023-08-08 13:27 UTC by nsstarr

## What's done
- ModalV2 now opens up near the trigger button instead of the top of the page
## How to test

## Tasks

- [ ] Have you written tests for new code (if applicable)?
- [ ] Have you tested the changes on all the platforms?
  - [x] iOS
  - [ ] Android
  - [ ] Web
- [x] Have you added stories to demonstrate the new functionality (if there is any)?

## Demo (screenshots, recordings, etc.)

2023-08-08 13:44 UTC, diegonzs-roll requested changes

2023-08-08 13:44 UTC, diegonzs-roll commented on packages/design-system/src/organisms/modalV2/index.tsx
> +  topPosition?: number
we can remove this one

2023-08-09 16:12 UTC, marlon-wiprud approved these changes

2023-08-09 16:19 UTC, diegonzs-roll approved these changes

2023-08-10 12:26 UTC, merged